/* Create Tables */

CREATE TABLE  "BANCO"
(
	"K_ID_REGLAS" NUMBER(8) NOT NULL,
	"V_MULTIPLO_N" NUMBER(5,2) NOT NULL,
	"T_TASA_INTERES" NUMBER(4,2) NOT NULL,
	"Q_PLAZO_MAXIMO" NUMBER(2) NOT NULL,
	"K_TIPO_CREDITO" NUMBER(3) NULL
)
;

CREATE TABLE  "CLIENTE"
(
	"K_IDENTIFICACION" NUMBER(11) NOT NULL,
	"I_TIPO_IDENTIFICACION" VARCHAR2(2) NOT NULL,
	"N_NOMBRE" VARCHAR2(30) NOT NULL,
	"N_APELLIDO" VARCHAR2(20) NOT NULL,
	"O_DIRECCION" VARCHAR2(30) NOT NULL,
	"O_TELEFONO" NUMBER(10) NOT NULL,
	"I_SEXO" CHAR(1) NOT NULL,
	"F_NACIMIENTO" DATE NOT NULL,
	"O_OCUPACION" VARCHAR2(20) NOT NULL,
	"O_CORREO_ELECTRONICO" VARCHAR2(40) NOT NULL,
	"V_INGRESO_MENSUAL" NUMBER(15,2) NOT NULL
)
;

CREATE TABLE  "CREDITO"
(
	"K_CREDITO" NUMBER(4) NOT NULL,
	"I_ESTADO" VARCHAR2(10) NOT NULL,
	"V_PENDIENTE" NUMBER(10,2) NOT NULL,
	"V_ULTIMO_PAGO" NUMBER(10,2) NULL,
	"F_ULTIMO_PAGO" DATE NULL,
	"F_APROBACION" DATE NOT NULL,
	"F_DESEMBOLSO" DATE NOT NULL,
	"V_PRESTADO" NUMBER(10,2) NOT NULL,
	"K_IDENTIFICACION" NUMBER(11) NULL,
	"K_TIPO_CREDITO" NUMBER(3) NULL
)
;

CREATE TABLE  "CUENTA_AHORRO"
(
	"K_NUM_CUENTA" NUMBER(10) NOT NULL,
	"I_ESTADO" VARCHAR2(9) NOT NULL,
	"V_SALDO" NUMBER(15,2) NOT NULL,
	"F_APERTURA" DATE NOT NULL,
	"K_IDENTIFICACION" NUMBER(11) NULL
)
;

CREATE TABLE  "EVENTO_CUENTA"
(
	"K_EVENTO" NUMBER(5) NOT NULL,
	"I_TIPO_EVENTO" VARCHAR2(15) NOT NULL,
	"F_EVENTO" DATE NOT NULL,
	"O_DESCRIPCION" VARCHAR2(30) NOT NULL,
	"K_NUM_CUENTA" NUMBER(10) NULL
)
;

CREATE TABLE  "MOVIMIENTO_CUENTA"
(
	"K_MOVIMIENTO" NUMBER(5) NOT NULL,
	"V_MOVIMIENTO" NUMBER(10,2) NOT NULL,
	"I_TIPO" VARCHAR2(7) NOT NULL,
	"F_MOVIMIENTO" TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
	"K_NUM_CUENTA" NUMBER(10) NULL
)
;

CREATE TABLE  "PAGO_CREDITO"
(
	"Q_CUOTA" NUMBER(2) NOT NULL,
	"F_PAGO_CREDITO" DATE NOT NULL,
	"Q_CONSIGNACION" NUMBER(10) NOT NULL,
	"I_FORMA_PAGO" VARCHAR2(8) NOT NULL,
	"V_PAGADO_CAPITAL" NUMBER(10,2) NOT NULL,
	"V_PAGADO_INTERESES" NUMBER(10,2) NOT NULL,
	"K_CREDITO" NUMBER(4) NULL
)
;

CREATE TABLE  "TIPO_CREDITO"
(
	"K_TIPO_CREDITO" NUMBER(3) NOT NULL,
	"T_INTERES" NUMBER(4,2) NOT NULL,
	"F_PLAZO_MAXIMO" DATE NOT NULL,
	"K_ID_REGLAS" NUMBER(8) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  "BANCO" 
 ADD CONSTRAINT "PK_BANCO"
	PRIMARY KEY ("K_ID_REGLAS") 
 USING INDEX
;

ALTER TABLE  "BANCO" 
 ADD CONSTRAINT "CK_V_MULTIPLO_N" CHECK (V_MULTIPLO_N>0)
;

ALTER TABLE  "BANCO" 
 ADD CONSTRAINT "CK_Q_PLAZO_MAXIMO" CHECK (Q_PLAZO_MAXIMO>0)
;

ALTER TABLE  "CLIENTE" 
 ADD CONSTRAINT "PK_CLIENTE"
	PRIMARY KEY ("K_IDENTIFICACION") 
 USING INDEX
;

ALTER TABLE  "CLIENTE" 
 ADD CONSTRAINT "UK_CORREO_ELECTRONICO" UNIQUE ("O_CORREO_ELECTRONICO") 
 USING INDEX
;

ALTER TABLE  "CLIENTE" 
 ADD CONSTRAINT "CK_SEXO" CHECK (I_SEXO = ('F','M'))
;

ALTER TABLE  "CLIENTE" 
 ADD CONSTRAINT "CK_INGRESO" CHECK (V_INGRESO_MENSUAL>0)
;

ALTER TABLE  "CLIENTE" 
 ADD CONSTRAINT "CK_IDENTIFICACION" CHECK (K_IDENTIFICACION>0)
;

ALTER TABLE  "CLIENTE" 
 ADD CONSTRAINT "CK_TIPO_IDENTIFICACION" CHECK (I_TIPO_IDENTIFICACION = ('CC','TI','CE'))
;

ALTER TABLE  "CREDITO" 
 ADD CONSTRAINT "PK_CREDITO"
	PRIMARY KEY ("K_CREDITO") 
 USING INDEX
;

ALTER TABLE  "CREDITO" 
 ADD CONSTRAINT "CK_ESTADO" CHECK (I_ESTADO = ('ACTIVA','INACTIVA','BLOQUEADA','activa','inactiva','bloqueada'))
;

ALTER TABLE  "CREDITO" 
 ADD CONSTRAINT "CK_V_PENDIENTE" CHECK (V_PENDIENTE>=0)
;

ALTER TABLE  "CREDITO" 
 ADD CONSTRAINT "CK_V_PRESTADO" CHECK (V_PRESTADO>0)
;

ALTER TABLE  "CUENTA_AHORRO" 
 ADD CONSTRAINT "PK_CUENTA_AHORRO"
	PRIMARY KEY ("K_NUM_CUENTA") 
 USING INDEX
;

ALTER TABLE  "CUENTA_AHORRO" 
 ADD CONSTRAINT "CK_SALDO" CHECK (V_SALDO>=0)
;

ALTER TABLE  "CUENTA_AHORRO" 
 ADD CONSTRAINT "CK_ESTADO" CHECK (I_ESTADO = ('ACTIVA','INACTIVA','BLOQUEADA','activa','inactiva','bloqueada'))
;

ALTER TABLE  "EVENTO_CUENTA" 
 ADD CONSTRAINT "PK_EVENTO_CUENTA"
	PRIMARY KEY ("K_EVENTO") 
 USING INDEX
;

ALTER TABLE  "EVENTO_CUENTA" 
 ADD CONSTRAINT "CK_TIPO_EVENTO" CHECK (I_TIPO_EVENTO = ('ACTIVACION','INACTIVACION','BLOQUEO'))
;

ALTER TABLE  "MOVIMIENTO_CUENTA" 
 ADD CONSTRAINT "PK_MOVIMIENTO_C_01"
	PRIMARY KEY ("K_MOVIMIENTO") 
 USING INDEX
;

ALTER TABLE  "MOVIMIENTO_CUENTA" 
 ADD CONSTRAINT "CK_TIPO" CHECK (I_TIPO = ('RETIRO','TRANSFERENCIA','CONSIGNACION'))
;

ALTER TABLE  "MOVIMIENTO_CUENTA" 
 ADD CONSTRAINT "CK_V_MOVIMIENTO" CHECK (V_MOVIMIENTO>0)
;

ALTER TABLE  "PAGO_CREDITO" 
 ADD CONSTRAINT "PK_PAGO_CREDITO"
	PRIMARY KEY ("Q_CUOTA") 
 USING INDEX
;

ALTER TABLE  "TIPO_CREDITO" 
 ADD CONSTRAINT "PK_TIPO_CREDITO"
	PRIMARY KEY ("K_TIPO_CREDITO") 
 USING INDEX
;

/* Create Foreign Key Constraints */

ALTER TABLE  "CREDITO" 
 ADD CONSTRAINT "FK_CREDITO_CLIENTE"
	FOREIGN KEY ("K_IDENTIFICACION") REFERENCES  "CLIENTE" ("K_IDENTIFICACION")
;

ALTER TABLE  "CREDITO" 
 ADD CONSTRAINT "FK_CREDITO_TIPO_CREDITO"
	FOREIGN KEY ("K_TIPO_CREDITO") REFERENCES  "TIPO_CREDITO" ("K_TIPO_CREDITO")
;

ALTER TABLE  "CUENTA_AHORRO" 
 ADD CONSTRAINT "FK_CUENTA_AHORRO_CLIENTE"
	FOREIGN KEY ("K_IDENTIFICACION") REFERENCES  "CLIENTE" ("K_IDENTIFICACION")
;

ALTER TABLE  "EVENTO_CUENTA" 
 ADD CONSTRAINT "FK_EVENTO_CUENTA_CUENTA_AHORRO"
	FOREIGN KEY ("K_NUM_CUENTA") REFERENCES  "CUENTA_AHORRO" ("K_NUM_CUENTA")
;

ALTER TABLE  "MOVIMIENTO_CUENTA" 
 ADD CONSTRAINT "FK_MOVIMIENTO_C_CUENTA_AHOR_01"
	FOREIGN KEY ("K_NUM_CUENTA") REFERENCES  "CUENTA_AHORRO" ("K_NUM_CUENTA")
;

ALTER TABLE  "PAGO_CREDITO" 
 ADD CONSTRAINT "FK_PAGO_CREDITO_CREDITO"
	FOREIGN KEY ("K_CREDITO") REFERENCES  "CREDITO" ("K_CREDITO")
;

ALTER TABLE  "TIPO_CREDITO" 
 ADD CONSTRAINT "FK_TIPO_CREDITO_BANCO"
	FOREIGN KEY ("K_ID_REGLAS") REFERENCES  "BANCO" ("K_ID_REGLAS")
;
